version: '3.6'

networks:
  movie-network:
    driver: bridge

services:
  movie-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=movie-mongo
    depends_on:
      - movie-mongo
    networks:
      - movie-network
    links:
      - movie-mongo
    container_name: movie-api
    command: yarn dev
    ports:
      - 3333:3333

  movie-mongo:
    image: bitnami/mongodb:latest
    container_name: movie-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongo:/bitnami
    networks:
      - movie-network
