version: '3.6'

networks:
  movie-network:
    driver: bridge

services:
  movie-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=movie-mongo
      - REDIS_URL=movie-redis
    depends_on:
      - movie-mongo
      - movie-redis
    networks:
      - movie-network
    links:
      - movie-mongo
      - movie-redis
    container_name: movie-api
    command: yarn dev
    ports:
      - 3333:3333

  movie-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - MONGO_URL=movie-mongo
      - REDIS_URL=movie-redis
    depends_on:
      - movie-mongo
      - movie-redis
    networks:
      - movie-network
    links:
      - movie-mongo
      - movie-redis
    container_name: movie-queue
    command: yarn queue

  movie-mongo:
    image: bitnami/mongodb:latest
    container_name: movie-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - movie-network

  movie-redis:
    image: bitnami/redis:latest
    container_name: movie-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - /tmp/redis:/bitnami/redis/data
    networks:
      - movie-network

